[build]
  publish = "."        # 发布目录设为根目录
  functions = "functions"  # 函数目录

[functions]
  node_bundler = "esbuild"
  [functions.settings]
    maxRequestBodySize = 50  # 单位：MB
    timeout = 30             # 单位：秒